repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.0
    hooks:
      - id: ruff
        files: ^(awesome_bioinfo|tests)/.*\.py$
        args: [--fix]
      - id: ruff-format
        files: ^(awesome_bioinfo|tests)/.*\.py$

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.0
    hooks:
      - id: check-yaml
        name: check-yaml-syntax
      - id: check-jsonschema
        name: validate-algorithm-schema
        files: ^data/algorithms/.*\.yaml$
        args: [--schemafile, schemas/algorithm-schema.json]
